features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://austgovt-inline_0.png'
favicon:
  use_default: false
  path: 'public://A_Black_Star_1.png'
  mimetype: image/png
