palette:
  top: '#055a8e'
  bottom: '#1d84c3'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#ffffff'
  button: '#007dab'
  buttonhover: '#0256b1'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#007dab'
logo: 'public://color/ausgov_barrio-55e8b507/logo.svg'
stylesheets:
  - 'public://color/ausgov_barrio-55e8b507/colors.css'
files:
  - 'public://color/ausgov_barrio-55e8b507/logo.svg'
  - 'public://color/ausgov_barrio-55e8b507/colors.css'
